<a href="https://colab.research.google.com/github/Anu4477/Data-science/blob/main/10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

creating array from list
1. 1D
2. 2D

In [ ]:
#list
import numpy as np
l = [1,2,3]
print(l)

#array 1d
arr = np.array(l)
print (arr)

#2D list
l = [[1,2,3],[4,5,6]]
print(l)
print(l[0])
print(l[0][0])

#2Darray
arr=np.array(l)
print(arr)

arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[0])
print(arr[0][0])

#question array value 4 ->100
l = [[1,2,3], [4,5,6]]
l[1][0] = 100
print(l)

print(np.array(l))


[1, 2, 3]
[1 2 3]
[[1, 2, 3], [4, 5, 6]]
[1, 2, 3]
1
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3]
1
[[1, 2, 3], [100, 5, 6]]
[[  1   2   3]
 [100   5   6]]


In [ ]:
#list
l = [1,2,3]
lm = l*2
print(lm)
# array
import numpy as np
arr = np.array(l)
arrM= arr*2
print(arrM)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [ ]:
# comparison
import time
start = time.time()
l=[i*2 for i in range(1000000)]
print("list output:",time.time() -start)

#array
import numpy as np
start= time.time()
arr= np. array(1000000)*2
print("array output:",time.time()-start)

list output: 0.07219243049621582
array output: 0.00014591217041015625


In [ ]:
# time taken by list and array
import time

# List timing
start = time.time()

l = [i * 2 for i in range(1000000)]

end = time.time()
print("Time taken by list:", end - start)

# NumPy array timing
start = time.time()

a = np.array(1000000) * 2

end = time.time()
print("Time taken by array:", end - start)

Time taken by list: 0.14721155166625977
Time taken by array: 0.0005209445953369141


In [ ]:
#zeros array 1D
import numpy as np
arr = np.zeros(5)
print(arr)

#zeros array 2D
arr = np.zeros((5,2))
print(arr)

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
#ones array 1D
import numpy as np
arr = np.ones(5)
print(arr)

#ones array 2D
arr = np.ones((5,2))
print(arr)

[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#zeros array 1D
import numpy as np
arr = np.zeros(5)
print(arr+10)

#zeros array 2D
arr = np.zeros((5,2))
print(arr+10)

[10. 10. 10. 10. 10.]
[[10. 10.]
 [10. 10.]
 [10. 10.]
 [10. 10.]
 [10. 10.]]


In [ ]:
#ones array 1D
import numpy as np
arr = np.ones(5)
print(arr+4)

#ones array 2D
arr = np.ones((5,2))
print(arr*5)

[5. 5. 5. 5. 5.]
[[5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]]


In [ ]:
import numpy as np

arr1 = np.zeros((2,2)) + 10
print(arr1)

[[10. 10.]
 [10. 10.]]


In [ ]:
import numpy as np
ar = np.zeros((2,3))
print(ar+10)
arr = np.ones((2,3))
print(arr*5)

[[10. 10. 10.]
 [10. 10. 10.]]
[[5. 5. 5.]
 [5. 5. 5.]]


In [ ]:
#full for 1D
import numpy as np
arr = np.full((3),5)
print(arr)

#full for 2D
import numpy as np
arr1 = np.full((2,3),5)
print(arr1)

[5 5 5]
[[5 5 5]
 [5 5 5]]


In [ ]:
#question helpof zeros ->2d ->6
#question helpof ones ->2d ->1
import numpy as np
arr=np.zeros((3,2))+6
print(arr)

arr1=np.full((3,2),1)
print(arr1)

[[6. 6.]
 [6. 6.]
 [6. 6.]]
[[1 1]
 [1 1]
 [1 1]]


In [ ]:
#random
# for 1D
import numpy as np
arr=np.random.random((5))
print(arr)

#f0r 2d
import numpy as np
arr=np.random.random((5,3))
print(arr)


[0.58908604 0.75318749 0.77956743 0.08324241 0.70801438]
[[0.61366045 0.48631948 0.66592325]
 [0.92492778 0.62749746 0.58253574]
 [0.74315565 0.91178294 0.0192126 ]
 [0.36375392 0.31957291 0.09667976]
 [0.2772874  0.89583356 0.61712516]]


In [ ]:
#arange
#for 1d
import numpy as np
arr=np.arange(5)
print(arr)

#for
arr1=np.arange(6).reshape(2,3)
print(arr1)



[0 1 2 3 4]
[[0 1 2]
 [3 4 5]]


**Vector(1d),matrix(2d),tensor(3d)**

In [ ]:
#vector 1d list
import numpy as np
l = [1,2,3]
print(l)

#array 1d
arr = np.array(l)
print (arr)


[1, 2, 3]
[1 2 3]


In [ ]:
#matrix 2d
import numpy as np
#2D list
l = [[1,2,3],[4,5,6]]
print(l)

#2Darray
arr=np.array(l)
print(arr)


[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
#tensor 3d
l=[[[1,2],[3,4]],[[5,6],[7,8]]]
print(l)

l = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])
print(l)

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Array properties
1. shape
2. dimensiom
3. size
4. dtype

In [ ]:
#array
import numpy as np
arr = np.arange(12).reshape(3,4)
print("shape:",np.shape(arr))
print("shape:",arr.shape)
print("dimension:",np.ndim(arr))
print("size:",np.size(arr))
print("data type:",arr.dtype)


shape: (3, 4)
shape: (3, 4)
dimension: 2
size: 12
data type: int64
