<a href="https://colab.research.google.com/github/Anu4477/Data-science/blob/main/11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Array resaping
1 . reshape()
2. flattten()->create copy
3. ravel()->retur original
4. transpose

In [ ]:
#reshape array
import numpy as np
arr=np.arange(12)
up_arr=np.reshape(arr,(3,4))
print(up_arr)

#example 2d
arr=np.arange(16)
up_arr=np.reshape(arr,(4,4))
print(up_arr)

#example 3d
arr=np.arange(16)
up_arr=np.reshape(arr,(2,2,4))
print(up_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [ ]:
#flatten 2d
# creates copy then work
import numpy as np
arr=np.arange(16).reshape(4,4)
print(arr)
up_arr=arr.flatten()
up_arr[0]=100
print(up_arr)
print(arr)

# example 3d
arr=np.arange(16).reshape(2,2,4)
print(arr)
up_arr=arr.flatten()
print(up_arr)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [ ]:
#reval
#Works on original array
import numpy as np
arr=np.arange(16).reshape(4,4)
print(arr)
up_arr=arr.ravel()
up_arr[0]=100
print(up_arr)

#for 3d
arr=np.arange(16).reshape(2,2,4)
print(arr)
up_arr=arr.ravel()
up_arr[0]=100
print(up_arr)
print(arr)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15]
[[[100   1   2   3]
  [  4   5   6   7]]

 [[  8   9  10  11]
  [ 12  13  14  15]]]


In [ ]:
#transpose
import numpy as np
arr=np.arange(16).reshape(4,4)
print(arr)
up_arr=arr.T
print(up_arr)
print("---------------------")

#for 3d
arr=np.arange(16).reshape(2,2,4)
print(arr)
up_arr=arr.T
print(up_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
---------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]


Numpy array operations
1. slicing for1d,2d,3d

In [ ]:
#slicing for 1d
import numpy as np
arr=np.arange(14)
print(arr)
up_arr=arr[:3]
print(up_arr)

print("---------------------")

#slicing for 2d
arr=np.arange(16).reshape(4,4)
print(arr)
up_arr=arr[1:3]
print(up_arr)

print("---------------------")

#slicing for 3d -> arange(24) -> 0,23
arr=np.arange(24).reshape(2,3,4)
print(arr)
up_arr=arr[0:2,0:2,0:2]
print(up_arr)





[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[0 1 2]
---------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
---------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1]
  [ 4  5]]

 [[12 13]
  [16 17]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1]
  [ 4  5]]

 [[12 13]
  [16 17]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1]
  [ 4  5]]

 [[12 13]
  [16 17]]]


**Looping with numpy**
1. while loop
2. for loop

In [ ]:
#while loop
import numpy as np
# for 1d
arr=np.arange(16)
i = 0
while i< len(arr):
 print(arr[i] , end=" ")
 i += 1

 # for 2d
arr = np.arange(12).reshape(3,4)

i = 0
while i < len(arr):
    j = 0
    while j < len(arr[i]):
        print(arr[i][j], end=" ")
        j += 1
    print()
    i += 1

print("----------------------------")
#  #for 3d
import numpy as np

arr = np.arange(24).reshape(2,3,4)

i = 0
while i < len(arr):
    j = 0
    while j < len(arr[i]):
        k = 0
        while k < len(arr[i][j]):
            print(arr[i][j][k], end=" ")
            k += 1
        print()
        j += 1
    print()
    i += 1


0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 0 1 2 3 
4 5 6 7 
8 9 10 11 
----------------------------
0 1 2 3 
4 5 6 7 
8 9 10 11 

12 13 14 15 
16 17 18 19 
20 21 22 23 



In [ ]:
#for loop
# for 1d
import numpy as np
arr=np.arange(16)
for i in arr:
  print(i,end=" ")
print()

  #for 2d
arr=np.arange(16).reshape(4,4)

for i in arr:
    for j in i:
      print(j,end=" ")
    print()


#for 3d
arr=np.arange(24).reshape(2,3,4)

for i in arr:
  for j in i:
    for k in j:
      print(k,end=" ")
    print()
print()

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 
0 1 2 3 
4 5 6 7 
8 9 10 11 
12 13 14 15 
0 1 2 3 
4 5 6 7 
8 9 10 11 
12 13 14 15 
16 17 18 19 
20 21 22 23 



Adding and removing data
