<a href="https://colab.research.google.com/github/Anu4477/Data-science/blob/main/12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**sorting**
1. sort() for 1d
2. sort() for 2d, use axis=0->cols,axis=1->rows
by default itsorts row wise

In [ ]:
#sort
#for 1d
import numpy as np
arr = np.array([10,40,30,60,90,7,5])
print(arr)
arr_s=np.sort(arr)
print(arr_s)

#for 2d
arr=np.array([[30,42,13],[20,11,34]])
print(arr)
arr_s=np.sort(arr)
arr_n=np.sort(arr,axis=0)
arr_p=np.sort(arr,axis=1)
print(arr_s)
print(arr_n)
print(arr_p)


#example 2
arr=np.array([[30,40,10],[12,54,23]])
print(arr)
arr_s=np.sort(arr)
print(arr_s)
arr_n=np.sort(arr,axis=0)
print(arr_n)
arr_p=np.sort(arr,axis=1)
print(arr_p)

#example
#sort in descending order
# for 1d
arr=np.array([10,40,30,60,90,7,5])
print(arr)
arr_s=np.sort(arr)
print(arr_s[::-1])

#example
#sort in descending order
# for 2d
arr=np.array([[10,40,30,60,90,7,5],[50,30,24,12,65,21,56]])
print(arr)
arr_s=np.sort(arr)[::-1]
print(arr_s)
arr_n=np.sort(arr,axis=0)[::-1]
print(arr_n)
arr_p=np.sort(arr,axis=1)[::-1]
print(arr_p)




[10 40 30 60 90  7  5]
[ 5  7 10 30 40 60 90]
[[30 42 13]
 [20 11 34]]
[[13 30 42]
 [11 20 34]]
[[20 11 13]
 [30 42 34]]
[[13 30 42]
 [11 20 34]]
[[30 40 10]
 [12 54 23]]
[[10 30 40]
 [12 23 54]]
[[12 40 10]
 [30 54 23]]
[[10 30 40]
 [12 23 54]]
[10 40 30 60 90  7  5]
[90 60 40 30 10  7  5]
[[10 40 30 60 90  7  5]
 [50 30 24 12 65 21 56]]
[[12 21 24 30 50 56 65]
 [ 5  7 10 30 40 60 90]]
[[50 40 30 60 90 21 56]
 [10 30 24 12 65  7  5]]
[[12 21 24 30 50 56 65]
 [ 5  7 10 30 40 60 90]]


FILTER
1. array[Expression]
2. array[array>2]||filter with mask

In [ ]:
#filter
#for 1d
import numpy as np
arr=np.array([10,20,40,6,3,4,2])
print(arr)
arr_f=arr[arr<40]
print(arr_f)

#for 2d
arr=np.array([[10,20,40,6,3,4,2],[125,120,140,6,130,4,2]])
print(arr)
arr_f=arr[arr>40]
print(arr_f)

#example
arr=np.array([10,20,40,6,3,4,2])
print(arr)
arr_f=arr[arr%2==0]
print(arr_f)

[10 20 40  6  3  4  2]
[10 20  6  3  4  2]
[[ 10  20  40   6   3   4   2]
 [125 120 140   6 130   4   2]]
[125 120 140 130]
[10 20 40  6  3  4  2]
[10 20 40  6  4  2]


**Fancy indexing vs np.where()**
1. array(list)
2. array([0,1,2])
3. np.where(expression)->ternary opr
4. np.where(array>2)
5.  np.where(array>2,array*2,array)
6. np.where(array>2,"true","false"

In [ ]:
#fancy indexing
import numpy as np
arr= np.array([10,20,3,4,90,100])
print(arr)
arr_f=arr[[0,2]]# 0 index value , 2 index value
print(arr_f)

#example
arr=np.array([29,39,47,54,67])
print(arr)
arr_f=arr[[0,2,4]]
print(arr_f)



[ 10  20   3   4  90 100]
[10  3]
[29 39 47 54 67]
[29 47 67]


In [ ]:
#np.where
import numpy as np
#1d
arr = np.array([10,3,4,80,30,40,9])
print(arr)
arr_w=np.where(arr>40,"true","false")
print(arr_w)

#example
arr = np.array([10,3,4,80,30,40,9])
print(arr)
arr_w=np.where(arr>40,arr+2,arr-2)
print(arr_w)
#if(arr>40):
 # (arr+2)
#else:
 # (arr-2)

 #example
import numpy as np
arr1 = np.array ([[12,234,3,53],
                 [34,6,78,25]])
print(arr1)
arr_wa= np.where(arr1%2==0, "true", "false")
print(arr_wa)


#example
import numpy as np
arr = np.array([10,20,30,40,50])
new_arr = np.where( arr> 40)
if new_arr[0].size > 0:  # Check if any elements satisfy the condition
    arr = arr + 2
else:
    arr = arr - 2
print(arr)

[10  3  4 80 30 40  9]
['false' 'false' 'false' 'true' 'false' 'false' 'false']
[10  3  4 80 30 40  9]
[ 8  1  2 82 28 38  7]
[[ 12 234   3  53]
 [ 34   6  78  25]]
[['true' 'true' 'false' 'false']
 ['true' 'true' 'true' 'false']]
[12 22 32 42 52]


**Adding and removing data**

In [ ]:
#concatenate
#for 1d
import numpy as np
arr1=np.array([10,20,30])
arr2=np.array([1,2,3])
arr1_arr2=np.concatenate((arr1,arr2))
print(arr1_arr2)



#for 2d
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr1_arr2=np.concatenate((arr1,arr2),axis=1)
print(arr1_arr2)

[10 20 30  1  2  3]
[11 22 33]
[[1 2 5 6]
 [3 4 7 8]]


**Statisticl functions**
1. np.sum(a)
-> Sum of all elements
2. np.mean(a)
-> Average = Sum of elements / Number of elements
3. np.median(a)
-> Middle value after sorting
4. np.min(a)
-> Smallest value in array
5. np.max(a)
-> Largest value in array
6. np.var(a) mean,difference,square,average | (sum = ddof)
-> divide by array length
7. np.std(a)
-> Standard Deviation = √Variance -> Measures spread of data
8. np.prod(a)
-> Multiplication of all elements
9. np.cumsum(a)
-> Cumulative (running) sum
10. np.cumprod(a)
-> Cumulative (running) product
11. np.argmin(a)
 -> Index position of minimum value
12. np.argmax(a)
 -> Index position of maximum value
13. np.abs(a)
-> Converts negative values to positive -> Absolute value (distance from zero)
14. np.unique(a)
 -> Returns unique values only -> Removes duplicates
15. np.percentile(a, 50)
-> Finds percentage-based value -> 50th percentile = Median
16. np.quantile(a, 0.5)
 -> Similar to percentile -> 0.5 = 50%
17. np.ptp(a)
-> Range = Max - Min
18. np.any(a)
 -> True if at least one value is True

In [ ]:
#np.sum
#for 1d
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
arr_s=np.sum(arr)
print(arr_s)
#for 2d
arr=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr)
arr_s=np.sum(arr)
print(arr_s)



[1 2 3 4 5]
15
[[1 2 3 4 5]
 [1 2 3 4 5]]
30


In [ ]:
#np.mean
#for 1d
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
arr_m=np.mean(arr)
print(arr_m)

[1 2 3 4 5]
3.0


In [ ]:
#np.median
#for 1d
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
arr_m=np.median(arr)
print(arr_m)

[1 2 3 4 5]
3.0


In [ ]:
#np.min
#for 1d
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
arr_m=np.min(arr)
print(arr_m)

[1 2 3 4 5]
1


In [ ]:
#np.max
#for 1d
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
arr_m=np.max(arr)
print(arr_m)

[1 2 3 4 5]
5


In [ ]:
#np.prod
#for 1d
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
arr_m=np.prod(arr)
print(arr_m)

[1 2 3 4 5]
120


In [ ]:
#np.argmin(a)
#for 1d
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
arr_m=np.argmin(arr)
print(arr_m)


[1 2 3 4 5]
0


In [ ]:
#np.argmax(a)
#for 1d
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
arr_m=np.argmax(arr)
print(arr_m)


[1 2 3 4 5]
4


In [ ]:
#np.unique(a)
#for 1d
import numpy as np
arr=np.array([1,5,4,2,3,4,1])
print(arr)
arr_m=np.unique(arr)
print(arr_m)

[1 5 4 2 3 4 1]
[1 2 3 4 5]


In [ ]:
#np.abs(a)
#for 1d
import numpy as np
arr=np.array([1,-6,2,-3,4,-9])
print(arr)
arr_m=np.abs(arr)
print(arr_m)


[ 1 -6  2 -3  4 -9]
[1 6 2 3 4 9]


In [ ]:
import numpy as np
a = np.array([1,2])/0
print(a)


[inf inf]


/tmp/ipykernel_6468/1913822612.py:2: RuntimeWarning: divide by zero encountered in divide
  a = np.array([1,2])/0
