<a href="https://colab.research.google.com/github/Anu4477/Data-science/blob/main/24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
from typing import ValuesView
#handle missing values
import pandas as pd
import numpy as np
data={
    "colors":['red','green','blue','orange','green','blue',np.nan]
}
df=pd.DataFrame(data)
#print(df)

#handle null Values
df.dropna(inplace=True)
print(df)

   colors
0     red
1   green
2    blue
3  orange
4   green
5    blue


In [15]:
#label encoding
#from sklearn.preprocessing import LabelEncoder

#method 1
# le=LabelEncoder()
# df['colors_encoder']=le.fit_transform(df['colors'])

#method2
# df['colors_encoder']=LabelEncoder().fit_transform(df['colors'])
# print(df)

#method 3
import sklearn
df['colors_encodder1']=sklearn.preprocessing.LabelEncoder().fit_transform(df['colors'])
print(df)

   colors  colors_encoder  colors_encodder1
0       3               3                 3
1       1               1                 1
2       0               0                 0
3       2               2                 2
4       1               1                 1
5       0               0                 0


In [25]:
#one hot encoding
from sklearn.preprocessing import OneHotEncoder
print(df)

#drop cols of label encodig
if 'colors_encoder' in df.keys():
 df.drop(df[['colors_encoder','colors_encodder1']],axis=1,inplace=True)
print(df)

#one hot encoding
#encoder=OneHotEncoder()
#encoder.fit_transform(df[['colors']])
#encoder_df=pd.DataFrame(encoder.fit_transform(df[['colors']]))
#df=df.join(encoder_df)
#print(df)

#one hot coding
df_encoder=pd.get_dummies(df,columns=['colors'])
print(df_encoder)



   colors    0    1    2    3
0       3  0.0  0.0  0.0  1.0
1       1  0.0  1.0  0.0  0.0
2       0  1.0  0.0  0.0  0.0
3       2  0.0  0.0  1.0  0.0
4       1  0.0  1.0  0.0  0.0
5       0  1.0  0.0  0.0  0.0
   colors    0    1    2    3
0       3  0.0  0.0  0.0  1.0
1       1  0.0  1.0  0.0  0.0
2       0  1.0  0.0  0.0  0.0
3       2  0.0  0.0  1.0  0.0
4       1  0.0  1.0  0.0  0.0
5       0  1.0  0.0  0.0  0.0
     0    1    2    3  colors_0  colors_1  colors_2  colors_3
0  0.0  0.0  0.0  1.0     False     False     False      True
1  0.0  1.0  0.0  0.0     False      True     False     False
2  1.0  0.0  0.0  0.0      True     False     False     False
3  0.0  0.0  1.0  0.0     False     False      True     False
4  0.0  1.0  0.0  0.0     False      True     False     False
5  1.0  0.0  0.0  0.0      True     False     False     False


In [26]:
#one hot encoding
from sklearn.preprocessing import OneHotEncoder
print(df)

#drop cols of label encodig
if 'colors_encoder' in df.keys():
 df.drop(df[['colors_encoder','colors_encodder1']],axis=1,inplace=True)
print(df)

#one hot coding
df_encoder=pd.get_dummies(df,columns=['colors'])
print(df_encoder)


   colors    0    1    2    3
0       3  0.0  0.0  0.0  1.0
1       1  0.0  1.0  0.0  0.0
2       0  1.0  0.0  0.0  0.0
3       2  0.0  0.0  1.0  0.0
4       1  0.0  1.0  0.0  0.0
5       0  1.0  0.0  0.0  0.0
   colors    0    1    2    3
0       3  0.0  0.0  0.0  1.0
1       1  0.0  1.0  0.0  0.0
2       0  1.0  0.0  0.0  0.0
3       2  0.0  0.0  1.0  0.0
4       1  0.0  1.0  0.0  0.0
5       0  1.0  0.0  0.0  0.0
     0    1    2    3  colors_0  colors_1  colors_2  colors_3
0  0.0  0.0  0.0  1.0     False     False     False      True
1  0.0  1.0  0.0  0.0     False      True     False     False
2  1.0  0.0  0.0  0.0      True     False     False     False
3  0.0  0.0  1.0  0.0     False     False      True     False
4  0.0  1.0  0.0  0.0     False      True     False     False
5  1.0  0.0  0.0  0.0      True     False     False     False


In [35]:
#combination of handling missing value/label encodiing/oe hot encoding
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

data={
    "age":[10,20,np.nan,26,30],
    "gender":['male','female','others','male',np.nan],
    "name":['dheeraj','kunal','nikita','pinky','yash']
}

df=pd.DataFrame(data)

#handle missing value
df['age']=df['age'].fillna(df['age'].mean())
df.dropna(subset=['gender'],inplace=True)
print(df)

#label encoding
le=LabelEncoder()
df['gender1']=le.fit_transform(df['gender'])
print(df)

#one hot encoding
oe=OneHotEncoder()
oe_e=oe.fit_transform(df[['gender']]).toarray()
print(oe_e)






    age  gender     name
0  10.0    male  dheeraj
1  20.0  female    kunal
2  21.5  others   nikita
3  26.0    male    pinky
    age  gender     name  gender1
0  10.0    male  dheeraj        1
1  20.0  female    kunal        0
2  21.5  others   nikita        2
3  26.0    male    pinky        1
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
