<a href="https://colab.research.google.com/github/Anu4477/Data-science/blob/main/9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

In [1]:
import numpy
print("hello")


hello


In [26]:
import numpy
#import numpy as np
#from numpy import arange
#from numpy import *
# n = numpy.arange(11)
# print(type(n))
# print(n)


#example
# n = numpy.arange(12)
# d = n. reshape(3,4)
# print(type(d))
# print(d)

# #example
# n= numpy.arange(12).reshape(4,3)
# print(n)

# example
# import numpy as np
# array_3d = np.array([
#     [[1, 2, 3], [4, 5, 6]],
#     [[7, 8, 9], [10, 11, 12]]
# ])

# print(array_3d)

#example
# n = numpy .arange(24).reshape(4,3,2)
# print(n)

#example split 2,5,8,11
n = numpy .arange(12).reshape(4,3)
print(n)
# print(n[:, 2])
# print(n[:,-1])
# print(n[0:4:,2])
# print(n[0:4,2:3])
print(n[1:3,1:2])
print(n[1:3,1])


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[4]
 [7]]
[4 7]
